version: 1.0.0.{build}
branches:
  only:
  - dev
configuration: Debug
init:
- git config --global core.autocrlf true
clone_folder: c:\projects\enjoycqrs
environment:
  COVERALLS_REPO_TOKEN:
    secure: k131M9lYqPhmepQEei/Q2U5Pz+PJ+PQ0Suz4s6PYE/E+Ssk+NAjqExcGOGqvtx/B
skip_commits:
  message: /updated readme.*/
platform: Any CPU
clone_depth: 1
before_build:
- cmd: nuget restore
build:
  project: EnjoyCQRS.sln
  verbosity: minimal
test_script:
- ps: . .\CodeCoverage.ps1 -Configuration $env:configuration